name: Ruby

on: [push, pull_request]

jobs:
  ue:
    name: ue (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby:
          - '3.1'
          - 'head'
        os:
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install rack
      run: gem install rack
    - name: Run tests
      run: rake
